// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Only the Prisma CLI (migrate, studio, ...) reads this; the app connects via
  // the pg adapter with DATABASE_URL. Prefer Neon's direct (non-pooler) URL for
  // migrations, since the pooler doesn't support the session features they need.
  datasource: {
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
